# Generated by Django 3.0.4 on 2020-04-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_userprofile_desctiption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='desctiption',
            new_name='description',
        ),
    ]
